version: "3"

services:
  db:
    image: postgres:13.2
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql-docker

volumes:
  pgdata:
